# Three-Address Code (TAC) - Optimized
# Generated by Minimal C Compiler
# Optimizations applied: Constant folding, Copy propagation
# ─────────────────────────────────────

 1: DECL y
 2: y = 10
 3: PRINT 10
