# Three-Address Code (TAC) - Optimized
# Generated by Minimal C Compiler
# Optimizations applied: Constant folding, Copy propagation
# ─────────────────────────────────────

 1: DECL x
 2: DECL y
 3: x = 5
 4: PRINT 5
